Create all-in-one node that can be booted from an AMI

diff --git a/debian/ellis.postinst b/debian/ellis.postinst
--- a/debian/ellis.postinst
+++ b/debian/ellis.postinst
@@ -87,10 +87,11 @@ case "$1" in
         cp $ELLIS_DIR/*.monit /etc/monit/conf.d/
         service monit restart
 
-        # Now tell monit to start ellis if it hasn't already.  The
-        # restart may not have happened yet, so monit may not yet have
-        # heard of ellis. In that case, start it ourselves.
-        monit start ellis || service ellis start
+        # Restart ellis.  Always do this by terminating ellis so monit will
+        # restart it more-or-less immediately.  (monit restart seems to have
+        # significant lag.)
+        # Don't fail if it's already stopped.
+        service ellis stop || /bin/true
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
@@ -102,9 +103,8 @@ case "$1" in
     ;;
 esac
 
-# dh_installdeb will replace this with shell code automatically
-# generated by other debhelper scripts.
-
-#DEBHELPER#
+if [ -x "/etc/init.d/ellis" ]; then
+        update-rc.d ellis defaults 60 40>/dev/null || exit $?
+fi
 
 exit 0
